// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: weather_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WeatherService_GetWeatherData_FullMethodName    = "/weather.WeatherService/GetWeatherData"
	WeatherService_StreamWeatherData_FullMethodName = "/weather.WeatherService/StreamWeatherData"
	WeatherService_SendWeatherData_FullMethodName   = "/weather.WeatherService/SendWeatherData"
)

// WeatherServiceClient is the client API for WeatherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WeatherServiceClient interface {
	// GetWeatherData RPC'si, belirli bir şehir için hava durumu verisi sağlar.
	GetWeatherData(ctx context.Context, in *WeatherRequest, opts ...grpc.CallOption) (*WeatherData, error)
	// StreamWeatherData RPC'si, sürekli hava durumu verisi akışı sağlar.
	StreamWeatherData(ctx context.Context, in *WeatherRequest, opts ...grpc.CallOption) (WeatherService_StreamWeatherDataClient, error)
	SendWeatherData(ctx context.Context, in *WeatherData, opts ...grpc.CallOption) (*WeatherResponse, error)
}

type weatherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeatherServiceClient(cc grpc.ClientConnInterface) WeatherServiceClient {
	return &weatherServiceClient{cc}
}

func (c *weatherServiceClient) GetWeatherData(ctx context.Context, in *WeatherRequest, opts ...grpc.CallOption) (*WeatherData, error) {
	out := new(WeatherData)
	err := c.cc.Invoke(ctx, WeatherService_GetWeatherData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weatherServiceClient) StreamWeatherData(ctx context.Context, in *WeatherRequest, opts ...grpc.CallOption) (WeatherService_StreamWeatherDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &WeatherService_ServiceDesc.Streams[0], WeatherService_StreamWeatherData_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &weatherServiceStreamWeatherDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WeatherService_StreamWeatherDataClient interface {
	Recv() (*WeatherData, error)
	grpc.ClientStream
}

type weatherServiceStreamWeatherDataClient struct {
	grpc.ClientStream
}

func (x *weatherServiceStreamWeatherDataClient) Recv() (*WeatherData, error) {
	m := new(WeatherData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *weatherServiceClient) SendWeatherData(ctx context.Context, in *WeatherData, opts ...grpc.CallOption) (*WeatherResponse, error) {
	out := new(WeatherResponse)
	err := c.cc.Invoke(ctx, WeatherService_SendWeatherData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeatherServiceServer is the server API for WeatherService service.
// All implementations must embed UnimplementedWeatherServiceServer
// for forward compatibility
type WeatherServiceServer interface {
	// GetWeatherData RPC'si, belirli bir şehir için hava durumu verisi sağlar.
	GetWeatherData(context.Context, *WeatherRequest) (*WeatherData, error)
	// StreamWeatherData RPC'si, sürekli hava durumu verisi akışı sağlar.
	StreamWeatherData(*WeatherRequest, WeatherService_StreamWeatherDataServer) error
	SendWeatherData(context.Context, *WeatherData) (*WeatherResponse, error)
	mustEmbedUnimplementedWeatherServiceServer()
}

// UnimplementedWeatherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWeatherServiceServer struct {
}

func (UnimplementedWeatherServiceServer) GetWeatherData(context.Context, *WeatherRequest) (*WeatherData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWeatherData not implemented")
}
func (UnimplementedWeatherServiceServer) StreamWeatherData(*WeatherRequest, WeatherService_StreamWeatherDataServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamWeatherData not implemented")
}
func (UnimplementedWeatherServiceServer) SendWeatherData(context.Context, *WeatherData) (*WeatherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendWeatherData not implemented")
}
func (UnimplementedWeatherServiceServer) mustEmbedUnimplementedWeatherServiceServer() {}

// UnsafeWeatherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeatherServiceServer will
// result in compilation errors.
type UnsafeWeatherServiceServer interface {
	mustEmbedUnimplementedWeatherServiceServer()
}

func RegisterWeatherServiceServer(s grpc.ServiceRegistrar, srv WeatherServiceServer) {
	s.RegisterService(&WeatherService_ServiceDesc, srv)
}

func _WeatherService_GetWeatherData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WeatherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherServiceServer).GetWeatherData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeatherService_GetWeatherData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherServiceServer).GetWeatherData(ctx, req.(*WeatherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeatherService_StreamWeatherData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WeatherRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WeatherServiceServer).StreamWeatherData(m, &weatherServiceStreamWeatherDataServer{stream})
}

type WeatherService_StreamWeatherDataServer interface {
	Send(*WeatherData) error
	grpc.ServerStream
}

type weatherServiceStreamWeatherDataServer struct {
	grpc.ServerStream
}

func (x *weatherServiceStreamWeatherDataServer) Send(m *WeatherData) error {
	return x.ServerStream.SendMsg(m)
}

func _WeatherService_SendWeatherData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WeatherData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherServiceServer).SendWeatherData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeatherService_SendWeatherData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherServiceServer).SendWeatherData(ctx, req.(*WeatherData))
	}
	return interceptor(ctx, in, info, handler)
}

// WeatherService_ServiceDesc is the grpc.ServiceDesc for WeatherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeatherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weather.WeatherService",
	HandlerType: (*WeatherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWeatherData",
			Handler:    _WeatherService_GetWeatherData_Handler,
		},
		{
			MethodName: "SendWeatherData",
			Handler:    _WeatherService_SendWeatherData_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamWeatherData",
			Handler:       _WeatherService_StreamWeatherData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "weather_service.proto",
}
